name: 2021-03
on: [push]

jobs:
  run:
    name: Answer
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Code
        run: php 2021/day-03/part2.php